server:
  port: 8084
  servlet:
    contextPath: /api
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:presbo_service_db}
    username: ${MYSQL_USERNAME:presbo-main-service-user}
    password: ${MYSQL_PASSWORD:Presbo@7855}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size:
        500MB
      max-request-size:
        500MB
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest